name: Pull raw data from OxCGRT Brazil non imputed API endpoint
on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.3
        with:
          path: main
          fetch-depth: 0
      - name: Download raw Brazil csv from OxCGRT database
        run: |
          curl 'http://oxcgrtportal.azurewebsites.net/api/csvdownload?type=subnational_brazil' -s -f -Lo 'OxCGRTBrazil_nonimputed_latest.csv'
   
      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          author_name: Saptarshi
          author_email: saptarshi3.14@gmail.com
          branch: main
          message: "Brazil data pull"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:  
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: main


