name: Pull raw data from OxCGRT Brazil non imputed API endpoint
on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.3
        with:
          path: main
          fetch-depth: 1
      - name: Download raw Brazil csv from OxCGRT database
        run: |
          curl 'http://oxcgrtportal.azurewebsites.net/api/csvdownload?type=subnational_brazil' -s -f -Lo 'OxCGRTBrazil_nonimputed_latest.csv'
   
      - name: Commit files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Add changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

