name: Pull raw data from OxCGRT Brazil non imputed API endpoint
on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.3
        with:
          path: main
          fetch-depth: 1
      - name: Download raw Brazil csv from OxCGRT database
        run: |
          curl 'http://oxcgrtportal.azurewebsites.net/api/csvdownload?type=subnational_brazil' -s -f -Lo 'OxCGRTBrazil_nonimputed_latest.csv'
   
      - name: Commit and push
        run: |
          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git pull github ${GITHUB_REF} --ff-only
          git add ...
          git commit -m "Latest brazil data"
          git push github HEAD:${GITHUB_REF}
